export const RELIABILITY_SERVICE_NAME = "MELKISM";

export const RELIABILITY_VERSION = "v6.2";

export const RELIABILITY_MAX_HEAP_WARNING_RATIO = 0.9;

export const RELIABILITY_MIN_UPTIME_SECONDS = 0;
