export const SECURITY_POSTURE_SERVICE = "MELKISM";

export const SECURITY_POSTURE_VERSION = "v6.9";

export const SECURITY_POSTURE_CONTROL_COUNT = 8;

export const SECURITY_POSTURE_SECRET_NAMES = [
  "DATABASE_URL",
  "DIRECT_URL",
  "JWT_SECRET",
  "SESSION_SECRET",
  "AUTH_SECRET",
  "NEXTAUTH_SECRET"
] as const;
