import type { SourceRegistryEntry } from "../registry/source.registry.types";

export const sourceCatalog: readonly SourceRegistryEntry[] = [
  {
    id: "world-bank",
    name: "World Bank",
    language: { primary: "en" },
    type: "international-organization",
    url: "https://www.worldbank.org/",
    enabled: true,
    priority: 10,
  },
  {
    id: "imf",
    name: "International Monetary Fund",
    language: { primary: "en" },
    type: "international-organization",
    url: "https://www.imf.org/",
    enabled: true,
    priority: 20,
  },
  {
    id: "un-habitat",
    name: "UN-Habitat",
    language: { primary: "en" },
    type: "international-organization",
    url: "https://unhabitat.org/",
    enabled: true,
    priority: 10,
  },
  {
    id: "oecd",
    name: "OECD",
    language: { primary: "en" },
    type: "international-organization",
    url: "https://www.oecd.org/",
    enabled: true,
    priority: 20,
  },
  {
    id: "eu-eurostat",
    name: "Eurostat",
    language: { primary: "en" },
    type: "official",
    url: "https://ec.europa.eu/eurostat/",
    enabled: true,
    priority: 30,
  },
  {
    id: "tcmb",
    name: "Türkiye Cumhuriyet Merkez Bankası",
    language: { primary: "tr" },
    type: "government",
    url: "https://www.tcmb.gov.tr/",
    enabled: true,
    priority: 10,
  },
  {
    id: "tuik",
    name: "Türkiye İstatistik Kurumu",
    language: { primary: "tr" },
    type: "government",
    url: "https://www.tuik.gov.tr/",
    enabled: true,
    priority: 10,
  },
  {
    id: "arab-habitat",
    name: "UN-Habitat Arab Region",
    language: { primary: "ar" },
    type: "international-organization",
    url: "https://unhabitat.org/",
    enabled: true,
    priority: 20,
  },
  {
    id: "un-arabic",
    name: "United Nations Arabic",
    language: { primary: "ar" },
    type: "international-organization",
    url: "https://www.un.org/ar/",
    enabled: true,
    priority: 20,
  },
  {
    id: "amar",
    name: "Amar",
    language: { primary: "fa" },
    type: "government",
    url: "https://www.amar.org.ir/",
    enabled: true,
    priority: 10,
  },
  {
    id: "cbi",
    name: "Central Bank of Iran",
    language: { primary: "fa" },
    type: "government",
    url: "https://www.cbi.ir/",
    enabled: true,
    priority: 10,
  },
  {
    id: "iran-stat",
    name: "Statistical Center of Iran",
    language: { primary: "fa" },
    type: "government",
    url: "https://www.amar.org.ir/",
    enabled: true,
    priority: 10,
  },
];