
export type {

GovernanceOptimizationEvolutionAdaptiveSelfImprovementV2InputContract,
GovernanceOptimizationEvolutionAdaptiveSelfImprovementV2RecordContract,
GovernanceOptimizationEvolutionAdaptiveSelfImprovementV2EvaluationContract

} from "./governance-optimization-evolution-adaptive-self-improvement.v2.contracts";

