export const PERFORMANCE_VERSION = "6.28.0";

export const MEMORY_CACHE_DEFAULT_TTL_MS = 30_000;

export const MEMORY_CACHE_DEFAULT_MAX_ENTRIES = 256;

export const MEMORY_CACHE_CLEANUP_INTERVAL_MS = 60_000;

export const PUBLIC_SHARED_CACHE_SECONDS = 60;

export const PUBLIC_STALE_WHILE_REVALIDATE_SECONDS = 300;

export const PUBLIC_BROWSER_CACHE_SECONDS = 0;

export const SEARCH_CACHE_TTL_MS = 15_000;

export const SEARCH_CACHE_MAX_ENTRIES = 128;
